version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION)"
  build:
    commands:
      - npm ci
      - make test
      - make build-image
      - bash npm-publish.sh
